/**
 * Prompt Duel — API Endpoint Tests
 *
 * Prerequisites:
 *   1. Backend running at http://localhost:3000
 *   2. Run setup first:  bun tests/setup.ts
 *
 * Run tests:  bun test tests/api.test.ts
 */

import { describe, test, expect, beforeAll } from 'bun:test';
import { readFileSync } from 'fs';
import { resolve } from 'path';

// ---------------------------------------------------------------------------
// Config — loaded from .env.test generated by setup.ts
// ---------------------------------------------------------------------------
let BASE_URL = 'http://localhost:3000';
let TOKEN_1 = '';
let TOKEN_2 = '';
let USER_1_ID = 0;
let USER_2_ID = 0;
let USER_1_NAME = '';
let USER_2_NAME = '';

beforeAll(() => {
  try {
    const envPath = resolve(__dirname, '.env.test');
    const content = readFileSync(envPath, 'utf-8');
    for (const line of content.split('\n')) {
      const [key, ...rest] = line.split('=');
      const value = rest.join('=').trim();
      if (key === 'BASE_URL') BASE_URL = value;
      if (key === 'TEST_TOKEN_1') TOKEN_1 = value;
      if (key === 'TEST_TOKEN_2') TOKEN_2 = value;
      if (key === 'TEST_USER_1_ID') USER_1_ID = parseInt(value);
      if (key === 'TEST_USER_2_ID') USER_2_ID = parseInt(value);
      if (key === 'TEST_USER_1_NAME') USER_1_NAME = value;
      if (key === 'TEST_USER_2_NAME') USER_2_NAME = value;
    }
  } catch (e) {
    throw new Error('Missing tests/.env.test — run "bun tests/setup.ts" first');
  }

  if (!TOKEN_1 || !TOKEN_2) {
    throw new Error('Tokens not loaded from .env.test');
  }
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function get(path: string, token?: string) {
  const headers: Record<string, string> = {};
  if (token) headers['Authorization'] = `Bearer ${token}`;
  return fetch(`${BASE_URL}${path}`, { headers });
}

function post(path: string, body?: object, token?: string) {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  return fetch(`${BASE_URL}${path}`, {
    method: 'POST',
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });
}

function del(path: string, token?: string) {
  const headers: Record<string, string> = {};
  if (token) headers['Authorization'] = `Bearer ${token}`;
  return fetch(`${BASE_URL}${path}`, { method: 'DELETE', headers });
}

// =========================================================================
// SECTION 1: UNPROTECTED ENDPOINTS
// =========================================================================
describe('Unprotected Endpoints', () => {
  // --- Root & Health ---
  describe('Root & Health', () => {
    test('GET / — returns API name', async () => {
      const res = await get('/');
      expect(res.status).toBe(200);
      const text = await res.text();
      expect(text).toContain('Prompt Duel');
    });

    test('GET /health — returns ok', async () => {
      const res = await get('/health');
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.status).toBe('ok');
    });
  });

  // --- Auth (Public) ---
  describe('Auth — Public', () => {
    // Short unique suffix to stay within 3-20 char username limit
    const uniqueSuffix = Math.random().toString(36).slice(2, 8);

    test('POST /auth/register — creates a new user', async () => {
      const res = await post('/auth/register', {
        username: `rt_${uniqueSuffix}`,
        email: `rt_${uniqueSuffix}@example.com`,
        password: 'testpass123',
      });
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.token).toBeTruthy();
      expect(json.user.username).toBe(`rt_${uniqueSuffix}`);
    });

    test('POST /auth/register — rejects duplicate username', async () => {
      const res = await post('/auth/register', {
        username: `rt_${uniqueSuffix}`,
        email: `rt_${uniqueSuffix}b@example.com`,
        password: 'testpass123',
      });
      expect(res.status).toBe(400);
      const json = await res.json() as any;
      expect(json.success).toBe(false);
    });

    test('POST /auth/login — valid credentials', async () => {
      const res = await post('/auth/login', {
        username: USER_1_NAME,
        password: 'testpass123',
      });
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.token).toBeTruthy();
    });

    test('POST /auth/login — invalid credentials', async () => {
      const res = await post('/auth/login', {
        username: USER_1_NAME,
        password: 'wrongpassword',
      });
      expect(res.status).toBe(401);
      const json = await res.json() as any;
      expect(json.success).toBe(false);
    });

    test('POST /auth/forgot-password — unknown email returns 404', async () => {
      const res = await post('/auth/forgot-password', {
        email: 'nonexistent@nowhere.com',
      });
      expect(res.status).toBe(404);
    });

    test('POST /auth/reset-password — invalid token returns 400', async () => {
      const res = await post('/auth/reset-password', {
        token: 'invalid-reset-token',
        password: 'newpassword123',
      });
      expect(res.status).toBe(400);
    });
  });

  // --- Legacy Data ---
  describe('Legacy Data Endpoints', () => {
    test('GET /users — returns array', async () => {
      const res = await get('/users');
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(Array.isArray(json)).toBe(true);
    });

    test('GET /prompts — returns array', async () => {
      const res = await get('/prompts');
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(Array.isArray(json)).toBe(true);
    });

    test('GET /duels — returns array', async () => {
      const res = await get('/duels');
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(Array.isArray(json)).toBe(true);
    });
  });

  // --- Leaderboard ---
  describe('Leaderboard', () => {
    test('GET /leaderboard — returns array', async () => {
      const res = await get('/leaderboard');
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(Array.isArray(json)).toBe(true);
    });

    test('GET /leaderboard/1 — returns array for challenge 1', async () => {
      const res = await get('/leaderboard/1');
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(Array.isArray(json)).toBe(true);
    });

    test('POST /leaderboard — saves entry', async () => {
      const res = await post('/leaderboard', {
        playerName: 'test_player',
        challenge: 1,
        score: 75,
        maxScore: 100,
        percentage: 75,
        grade: 'B',
        promptsUsed: 3,
      });
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
    });
  });

  // --- Evaluation ---
  describe('Evaluation', () => {
    test('POST /evaluate-player — returns score', async () => {
      const res = await post('/evaluate-player', {
        playerName: 'nonexistent_player',
        challenge: 1,
      });
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      // May succeed or fail depending on workspace existence, but should return 200
      expect(json).toHaveProperty('success');
    });

    test('POST /evaluate — returns both player results', async () => {
      const res = await post('/evaluate', {
        player1Name: 'nonexistent_p1',
        player2Name: 'nonexistent_p2',
        challenge: 1,
      });
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json).toHaveProperty('success');
    });
  });

  // --- Challenge Prompts ---
  describe('Challenge Prompts', () => {
    test('GET /challenge-prompts/1 — returns prompts', async () => {
      const res = await get('/challenge-prompts/1');
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
    });
  });
});

// =========================================================================
// SECTION 2: PROTECTED ENDPOINTS — WITHOUT TOKEN (should 401)
// =========================================================================
describe('Protected Endpoints — No Token (expect 401)', () => {
  test('GET /auth/me — 401', async () => {
    const res = await get('/auth/me');
    expect(res.status).toBe(401);
  });

  test('POST /auth/logout — 401', async () => {
    const res = await post('/auth/logout');
    expect(res.status).toBe(401);
  });

  test('POST /auth/change-password — 401', async () => {
    const res = await post('/auth/change-password', {
      currentPassword: 'x',
      newPassword: 'y12345',
    });
    expect(res.status).toBe(401);
  });

  test('GET /rooms/ — 401', async () => {
    const res = await get('/rooms/');
    expect(res.status).toBe(401);
  });

  test('POST /rooms/ — 401', async () => {
    const res = await post('/rooms/', { challenge: 1 });
    expect(res.status).toBe(401);
  });

  test('GET /rooms/FAKECODE — 401', async () => {
    const res = await get('/rooms/FAKECODE');
    expect(res.status).toBe(401);
  });

  test('POST /rooms/FAKECODE/join — 401', async () => {
    const res = await post('/rooms/FAKECODE/join');
    expect(res.status).toBe(401);
  });

  test('POST /rooms/FAKECODE/spectate — 401', async () => {
    const res = await post('/rooms/FAKECODE/spectate');
    expect(res.status).toBe(401);
  });

  test('POST /rooms/FAKECODE/ready — 401', async () => {
    const res = await post('/rooms/FAKECODE/ready');
    expect(res.status).toBe(401);
  });

  test('POST /rooms/FAKECODE/start — 401', async () => {
    const res = await post('/rooms/FAKECODE/start');
    expect(res.status).toBe(401);
  });

  test('POST /rooms/FAKECODE/leave — 401', async () => {
    const res = await post('/rooms/FAKECODE/leave');
    expect(res.status).toBe(401);
  });

  test('POST /rooms/FAKECODE/finish — 401', async () => {
    const res = await post('/rooms/FAKECODE/finish');
    expect(res.status).toBe(401);
  });

  test('POST /rooms/FAKECODE/provider — 401', async () => {
    const res = await post('/rooms/FAKECODE/provider', {
      provider: 'anthropic',
      model: 'claude-sonnet-4-20250514',
    });
    expect(res.status).toBe(401);
  });

  test('POST /rooms/FAKECODE/penalty — 401', async () => {
    const res = await post('/rooms/FAKECODE/penalty', {
      playerNum: 1,
      penalty: 10,
    });
    expect(res.status).toBe(401);
  });

  test('POST /rooms/FAKECODE/results — 401', async () => {
    const res = await post('/rooms/FAKECODE/results', {});
    expect(res.status).toBe(401);
  });

  test('DELETE /rooms/FAKECODE — 401', async () => {
    const res = await del('/rooms/FAKECODE');
    expect(res.status).toBe(401);
  });

  test('GET /chat/FAKECODE — 401', async () => {
    const res = await get('/chat/FAKECODE');
    expect(res.status).toBe(401);
  });

  test('POST /chat/FAKECODE — 401', async () => {
    const res = await post('/chat/FAKECODE', { message: 'hello' });
    expect(res.status).toBe(401);
  });
});

// =========================================================================
// SECTION 3: PROTECTED ENDPOINTS — WITH TOKEN (happy path)
// =========================================================================
describe('Protected Endpoints — With Token', () => {
  // --- Auth ---
  describe('Auth — Protected', () => {
    test('GET /auth/me — returns user info', async () => {
      const res = await get('/auth/me', TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.user.username).toBe(USER_1_NAME);
    });
  });

  // --- Full Room Lifecycle ---
  describe('Room Lifecycle (create -> join -> ready -> start -> finish -> delete)', () => {
    let roomCode = '';

    test('POST /rooms/ — create room', async () => {
      const res = await post('/rooms/', { challenge: 1, timerMinutes: 20 }, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.room.code).toBeTruthy();
      roomCode = json.room.code;
    });

    test('GET /rooms/ — list rooms includes created room', async () => {
      const res = await get('/rooms/', TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      const found = json.rooms.find((r: any) => r.code === roomCode);
      expect(found).toBeTruthy();
      expect(found.hostUsername).toBe(USER_1_NAME);
    });

    test('GET /rooms/:code — room detail', async () => {
      const res = await get(`/rooms/${roomCode}`, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.room.code).toBe(roomCode);
      expect(json.room.status).toBe('waiting');
      expect(json.room.host.username).toBe(USER_1_NAME);
    });

    test('POST /rooms/:code/provider — set provider', async () => {
      const res = await post(`/rooms/${roomCode}/provider`, {
        provider: 'anthropic',
        model: 'claude-sonnet-4-20250514',
      }, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
    });

    test('POST /rooms/:code/join — user2 joins as player', async () => {
      const res = await post(`/rooms/${roomCode}/join`, undefined, TOKEN_2);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
    });

    test('POST /rooms/:code/ready — user1 readies up', async () => {
      const res = await post(`/rooms/${roomCode}/ready`, undefined, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.player1Ready).toBe(true);
    });

    test('POST /rooms/:code/ready — user2 readies up', async () => {
      const res = await post(`/rooms/${roomCode}/ready`, undefined, TOKEN_2);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.player2Ready).toBe(true);
    });

    test('POST /rooms/:code/start — host starts game', async () => {
      const res = await post(`/rooms/${roomCode}/start`, undefined, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.status).toBe('playing');
    });

    test('GET /rooms/:code — status is now playing', async () => {
      const res = await get(`/rooms/${roomCode}`, TOKEN_1);
      const json = await res.json() as any;
      expect(json.room.status).toBe('playing');
    });

    test('POST /rooms/:code/penalty — update penalty', async () => {
      const res = await post(`/rooms/${roomCode}/penalty`, {
        playerNum: 1,
        penalty: 10,
      }, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.penalty).toBe(10);
    });

    test('POST /rooms/:code/results — save results', async () => {
      const res = await post(`/rooms/${roomCode}/results`, {
        player1Score: 80,
        player2Score: 70,
        player1PromptsUsed: 3,
        player2PromptsUsed: 4,
        winnerId: USER_1_ID,
      }, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
    });

    test('POST /rooms/:code/finish — mark finished', async () => {
      const res = await post(`/rooms/${roomCode}/finish`, undefined, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
    });

    test('GET /rooms/:code — status is now finished', async () => {
      const res = await get(`/rooms/${roomCode}`, TOKEN_1);
      const json = await res.json() as any;
      expect(json.room.status).toBe('finished');
      expect(json.room.player1Score).toBe(80);
      expect(json.room.player2Score).toBe(70);
      expect(json.room.winnerId).toBe(USER_1_ID);
    });

    test('DELETE /rooms/:code — host deletes room', async () => {
      const res = await del(`/rooms/${roomCode}`, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
    });

    test('GET /rooms/:code — deleted room returns 404', async () => {
      const res = await get(`/rooms/${roomCode}`, TOKEN_1);
      expect(res.status).toBe(404);
    });
  });

  // --- Room Edge Cases ---
  describe('Room Edge Cases', () => {
    test('GET /rooms/NONEXIST — 404', async () => {
      const res = await get('/rooms/NONEXIST', TOKEN_1);
      expect(res.status).toBe(404);
    });

    test('POST /rooms/NONEXIST/join — 404', async () => {
      const res = await post('/rooms/NONEXIST/join', undefined, TOKEN_1);
      expect(res.status).toBe(404);
    });

    test('POST /rooms/NONEXIST/start — 404', async () => {
      const res = await post('/rooms/NONEXIST/start', undefined, TOKEN_1);
      expect(res.status).toBe(404);
    });

    test('DELETE /rooms/NONEXIST — 404', async () => {
      const res = await del('/rooms/NONEXIST', TOKEN_1);
      expect(res.status).toBe(404);
    });
  });

  // --- Spectator Flow ---
  describe('Spectator Flow', () => {
    let roomCode = '';

    test('Setup: create room with user1', async () => {
      const res = await post('/rooms/', { challenge: 2, timerMinutes: 30 }, TOKEN_1);
      const json = await res.json() as any;
      roomCode = json.room.code;
      expect(roomCode).toBeTruthy();
    });

    test('POST /rooms/:code/spectate — user2 spectates', async () => {
      const res = await post(`/rooms/${roomCode}/spectate`, undefined, TOKEN_2);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
    });

    test('GET /rooms/:code — spectator count is 1', async () => {
      const res = await get(`/rooms/${roomCode}`, TOKEN_1);
      const json = await res.json() as any;
      expect(json.room.spectators.length).toBe(1);
      expect(json.room.spectators[0].username).toBe(USER_2_NAME);
    });

    test('POST /rooms/:code/spectate — already spectating returns success', async () => {
      const res = await post(`/rooms/${roomCode}/spectate`, undefined, TOKEN_2);
      expect(res.status).toBe(200);
    });

    test('Cleanup: delete room', async () => {
      const res = await del(`/rooms/${roomCode}`, TOKEN_1);
      expect(res.status).toBe(200);
    });
  });

  // --- Chat ---
  describe('Chat', () => {
    let roomCode = '';

    test('Setup: create room and join', async () => {
      const res = await post('/rooms/', { challenge: 1 }, TOKEN_1);
      const json = await res.json() as any;
      roomCode = json.room.code;

      // User 2 joins as player
      await post(`/rooms/${roomCode}/join`, undefined, TOKEN_2);
    });

    test('POST /chat/:roomCode — send message', async () => {
      const res = await post(`/chat/${roomCode}`, { message: 'Hello from tests!' }, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.message.message).toBe('Hello from tests!');
      expect(json.message.username).toBe(USER_1_NAME);
    });

    test('GET /chat/:roomCode — get messages', async () => {
      const res = await get(`/chat/${roomCode}`, TOKEN_1);
      expect(res.status).toBe(200);
      const json = await res.json() as any;
      expect(json.success).toBe(true);
      expect(json.messages.length).toBeGreaterThanOrEqual(1);
      expect(json.messages.some((m: any) => m.message === 'Hello from tests!')).toBe(true);
    });

    test('GET /chat/NONEXIST — 404 for nonexistent room', async () => {
      const res = await get('/chat/NONEXIST', TOKEN_1);
      expect(res.status).toBe(404);
    });

    test('Cleanup: delete room', async () => {
      await del(`/rooms/${roomCode}`, TOKEN_1);
    });
  });

  // --- Leave Room ---
  describe('Leave Room', () => {
    let roomCode = '';

    test('Setup: create room, user2 joins', async () => {
      const res = await post('/rooms/', { challenge: 1 }, TOKEN_1);
      const json = await res.json() as any;
      roomCode = json.room.code;

      await post(`/rooms/${roomCode}/join`, undefined, TOKEN_2);
    });

    test('POST /rooms/:code/leave — player2 leaves', async () => {
      const res = await post(`/rooms/${roomCode}/leave`, undefined, TOKEN_2);
      expect(res.status).toBe(200);
    });

    test('GET /rooms/:code — player2 slot is empty after leaving', async () => {
      const res = await get(`/rooms/${roomCode}`, TOKEN_1);
      const json = await res.json() as any;
      expect(json.room.player2).toBe(null);
    });

    test('Cleanup: delete room', async () => {
      await del(`/rooms/${roomCode}`, TOKEN_1);
    });
  });

  // --- Authorization Checks ---
  describe('Authorization Checks', () => {
    let roomCode = '';

    test('Setup: create room with user1', async () => {
      const res = await post('/rooms/', { challenge: 1 }, TOKEN_1);
      const json = await res.json() as any;
      roomCode = json.room.code;
    });

    test('POST /rooms/:code/start — non-host cannot start', async () => {
      // User2 joins first
      await post(`/rooms/${roomCode}/join`, undefined, TOKEN_2);
      const res = await post(`/rooms/${roomCode}/start`, undefined, TOKEN_2);
      expect(res.status).toBe(403);
    });

    test('DELETE /rooms/:code — non-host cannot delete', async () => {
      const res = await del(`/rooms/${roomCode}`, TOKEN_2);
      expect(res.status).toBe(403);
    });

    test('Cleanup: delete room', async () => {
      await del(`/rooms/${roomCode}`, TOKEN_1);
    });
  });

  // --- Invalid Token ---
  describe('Invalid Token', () => {
    test('GET /auth/me — invalid token returns 401', async () => {
      const res = await get('/auth/me', 'invalid.jwt.token');
      expect(res.status).toBe(401);
    });

    test('GET /rooms/ — invalid token returns 401', async () => {
      const res = await get('/rooms/', 'totally-bogus-token');
      expect(res.status).toBe(401);
    });
  });
});
